title: "Little Note"
author: "Apip"
description: "Â© 2025"

url: "https://apip-web.github.io"
baseurl: "/mouse"

collections:
  blog:
    output: true
    permalink: /blog/:name/

rss: rss

kramdown:
  syntax_highlighter_opts:
    disable: false

plugins:
  - jekyll-feed
  - jekyll-sitemap
